### ISSUE TITLE
Strip off leading/remaing spaces

### ISSUE THREAD

**Issue by rusco** [owlfish/tal#1]
Question: 
is there a possibility to strip off leading/remaining spaces similiar to Go1.6 templates, see:
https://tip.golang.org/pkg/text/template/#hdr-Text_and_spaces  ?

**Comment by cms103** [comment]
There isn't any standard TAL command that would do this and I'm not aware of any extensions to the language in other implementations that would achieve the same effect.

I'm curious as to what scenario this would be useful in.  The Go template example given doesn't really have a strong analogy in TAL.  As the tal package implements only for HTML5, removing stray whitespace is of no real value due to the whitespace handling rules in HTML.  

Text substitutions of the kind shown in the Go template example are usually handled with a string: TALES expression.  As the string needs to be contained in a valid attribute, spreading it over multiple lines as shown in the Go example is not something that is normally done.

**Comment by cms103** [comment]
Closing as it's unclear what is being requested.
